IMPORT TABLE movies (
  imdb_title_id VARCHAR(256) PRIMARY KEY,
  title TEXT,
  original_title TEXT,
  year_published INTEGER,
  date_published TEXT,
  genre TEXT,
  duration INTEGER,
  country TEXT,
  language TEXT,
  director TEXT,
  writer TEXT,
  production_company TEXT,
  actors TEXT,
  description TEXT,
  avg_vote FLOAT8,
  votes INTEGER,
  budget TEXT,
  usa_gross_income TEXT,
  worldwide_gross_income TEXT,
  metascore FLOAT8,
  reviews_from_users TEXT,
  reviews_from_critics TEXT
) CSV DATA ('nodelocal://self/IMDbmovies.csv') WITH skip = '1';

IMPORT TABLE ratings(
  imdb_title_id VARCHAR(256) PRIMARY KEY,
  weighted_average_vote FLOAT8,
  total_votes FLOAT8,
  mean_vote FLOAT8,
  median_vote FLOAT8,
  votes_10 FLOAT8, 
  votes_9 FLOAT8, 
  votes_8 FLOAT8, 
  votes_7 FLOAT8, 
  votes_6 FLOAT8, 
  votes_5 FLOAT8, 
  votes_4 FLOAT8, 
  votes_3 FLOAT8, 
  votes_2 FLOAT8, 
  votes_1 FLOAT8, 
  allgenders_0age_avg_vote FLOAT8, 
  allgenders_0age_votes FLOAT8, 
  allgenders_18age_avg_vote FLOAT8, 
  allgenders_18age_votes FLOAT8, 
  allgenders_30age_avg_vote FLOAT8, 
  allgenders_30age_votes FLOAT8, 
  allgenders_45age_avg_vote FLOAT8, 
  allgenders_45age_votes FLOAT8, 
  males_allages_avg_vote FLOAT8,
  males_allages_votes FLOAT8, 
  males_0age_avg_vote FLOAT8, 
  males_0age_votes FLOAT8, 
  males_18age_avg_vote FLOAT8,
  males_18age_votes FLOAT8, 
  males_30age_avg_vote FLOAT8, 
  males_30age_votes FLOAT8, 
  males_45age_avg_vote FLOAT8, 
  males_45age_votes FLOAT8, 
  females_allages_avg_vote FLOAT8, 
  females_allages_votes FLOAT8, 
  females_0age_avg_vote FLOAT8, 
  females_0age_votes FLOAT8, 
  females_18age_avg_vote FLOAT8, 
  females_18age_votes FLOAT8, 
  females_30age_avg_vote FLOAT8, 
  females_30age_votes FLOAT8, 
  females_45age_avg_vote FLOAT8, 
  females_45age_votes FLOAT8, 
  top1000_voters_rating FLOAT8, 
  top1000_voters_votes FLOAT8, 
  us_voters_rating FLOAT8, 
  us_voters_votes FLOAT8, 
  non_us_voters_rating FLOAT8, 
  non_us_voters_votes FLOAT8
) CSV DATA ('nodelocal://self/IMDbratings.csv') WITH skip = '1', nullif='';

IMPORT table movie_principals(
  imdb_title_id VARCHAR(256),
  ordering INTEGER,
  imdb_name_id VARCHAR(256),
  category TEXT,
  job TEXT,
  characters TEXT
) CSV DATA ('nodelocal://self/IMDbtitle_principals.csv') WITH skip = '1', nullif='';

IMPORT TABLE movie_principals(
  imdb_title_id,
  ordering,
  imdb_name_id,
  category,
  job,
  characters
) CSV DATA ('nodelocal://self/IMDbtitle_principals.csv') WITH skip = '1', nullif='';

IMPORT TABLE names(
  imdb_name_id VARCHAR(256) PRIMARY KEY,
  name TEXT,
  birth_name TEXT,
  height INTEGER,
  bio TEXT,
  birth_details TEXT,
  date_of_birth TEXT,
  place_of_birth TEXT,
  death_details TEXT,
  date_of_death TEXT,
  place_of_death TEXT,
  reason_of_death TEXT,
  spouses_string TEXT,
  spouses TEXT,
  divorces TEXT,
  spouses_with_children TEXT,
  children TEXT
) CSV DATA ('nodelocal://self/IMDbnames.csv') WITH skip = '1', nullif='';